apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubble.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: hubble-ui
          port: 80
  tls:
    secretName: hubble-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ingress-certificate
spec:
  secretName: hubble-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - hubble.home.jonahsserver.com
