apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`umami.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: umami-service
          port: 3000
  tls:
    secretName: umami-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: umami-ingress-certificate
spec:
  secretName: umami-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - umami.home.jonahsserver.com
