apiVersion: v1
kind: Service
metadata:
  name: umami-service
  labels:
    app: umami
spec:
  type: ClusterIP
  selector:
    app: umami
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
