apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`searxng.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: searxng
          port: 8888
          scheme: http
  tls:
    secretName: searxng-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-ingress-certificate
spec:
  secretName: searxng-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - searxng.home.jonahsserver.com
