apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-repo.yaml
  - sealed-ui-creds.yaml
  - sealed-has-webhook.yaml
  - release.yaml
  - alert-manager-config.yaml
  - ingress.yaml
