apiVersion: v1
kind: Service
metadata:
  name: alp-web-service
  namespace: aprilslilpugs
spec:
  selector:
    app: alp-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
