kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter-proxmox
  labels:
    app: exporter-proxmox
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exporter-proxmox
  template:
    metadata:
      labels:
        app: exporter-proxmox
    spec:
      containers:
        - name: exporter-proxmox
          image: prompve/prometheus-pve-exporter:3.8.0
          env:
            - name: PVE_USER
              value: "prometheus@pam"
            - name: PVE_TOKEN_NAME
              value: "exporter"
            - name: PVE_TOKEN_VALUE
              valueFrom:
                secretKeyRef:
                  name: proxmox-exporter-secret
                  key: pveApiToken
            - name: PVE_VERIFY_SSL
              value: "false"
