apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  labels:
    app: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.32.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9130
              name: prometheus
          volumeMounts:
            - name: config
              mountPath: /etc/unpoller/up.conf
              subPath: up.conf
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: unpoller-config
