apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - sealed-unify-creds.yaml
  - deployment.yaml
  - service.yaml
  - ap-dashboard.yaml
  - clients-dashboard.yaml
  - gateway-dashboard.yaml
  - switch-dashboard.yaml
  - dpi-dashboard.yaml
