apiVersion: v1
kind: Service
metadata:
  name: unpoller
  labels:
    app: unpoller
spec:
  type: ClusterIP
  ports:
    - port: 9130
      targetPort: 9130
      protocol: TCP
      name: prometheus
  selector:
    app: unpoller
