apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pterodactyl-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pterodactyl.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: pterodactyl
          port: 80
          scheme: http
          serversTransport: pterodactyl-insecure-transport
  tls:
    secretName: pterodactyl-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pterodactyl-ingress-certificate
spec:
  secretName: pterodactyl-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - pterodactyl.home.jonahsserver.com
