apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    color: zinc
    theme: dark
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Dev & Ops:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: github.png
        - Docker Hub:
            - abbr: DH
              href: https://hub.docker.com/
              icon: docker.png
        - Helm Charts:
            - abbr: HC
              href: https://artifacthub.io/
              icon: helm.png
  services.yaml: |
    - IoT & Smarthome:
        - Home Assistant:
            icon: home-assistant.png
            href: {{HOMEPAGE_VAR_HAS_URL}}
        - Homebridge:
            icon: homebridge.png
            href: https://homebridge.home.jonahsserver.com

    - Infrastructure & Data:
        - PVE-0:
            icon: proxmox.png
            href: https://pve-0.home.jonahsserver.com/
            widget:
              type: proxmox
              url: {{HOMEPAGE_VAR_PROXMOX_PVE0_URL}}
              username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_API_TOKEN}}"
              node: oswald-pve-0
              fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
        - TrueNAS:
            icon: truenas.png
            href: https://truenas.home.jonahsserver.com/
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.home.jonahsserver.com/

    - Networking:
        - Unify:
            icon: ubiquiti.png
            href: https://unify.home.jonahsserver.com/
        - PiHole:
            icon: pi-hole.png
            href: https://pihole.home.jonahsserver.com/
            widget:
              type: pihole
              url: http://pihole-web.pihole
              version: 6
              key: {{HOMEPAGE_VAR_PIHOLE_PASSWORD}}
              fields: ["queries", "blocked", "blocked_percent", "gravity"]
        - NPM:
            icon: nginx-proxy-manager.png
            href: https://npm.home.jonahsserver.com/
            widget:
              type: npm
              url: {{HOMEPAGE_VAR_NPM_URL}}
              username: {{HOMEPAGE_VAR_NPM_USERNAME}}
              password: {{HOMEPAGE_VAR_NPM_PASSWORD}}
              fields: ["enabled", "disabled", "total"]

    - Monitoring & Management:
        - Grafana:
            icon: grafana.png
            href: https://grafana.home.jonahsserver.com/
        - Portainer:
            icon: portainer.png
            href: https://portainer.home.jonahsserver.com/
            widget:
              type: portainer
              url: {{HOMEPAGE_VAR_PORTAINER_URL}}
              env: 3
              key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
              fields: ["running", "stopped", "total"]

    - Minecraft:
        - Vanilla:
            icon: minecraft.png
            href: https://crafty.home.jonahsserver.com/
            widget:
              type: minecraft
              url: {{HOMEPAGE_VAR_MINECRAFT_URL_VANILLA}}
              fields: ["players", "version", "status"]
        - Modded:
            icon: minecraft.png
            href: https://crafty.home.jonahsserver.com/
            widget:
              type: minecraft
              url: {{HOMEPAGE_VAR_MINECRAFT_URL_MODDED}}
              fields: ["players", "version", "status"]

    - AI:
        - OpenWebUI:
            icon: open-webui.png
            href: https://oswald.home.jonahsserver.com/

    - Security:
        - Vaultwarden:
            icon: vaultwarden.png
            href: https://vaultwarden.home.jonahsserver.com/
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
        include:
          - node1
          - node2
          - node3
  docker.yaml: ""
