apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./pve-0
  - ./portainer
  - ./crafty
  - ./unify
  - ./truenas
  - ./npm
  - ./homebridge
  - ./searxng
