apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: minio
          port: 9001
          scheme: https
  tls:
    secretName: minio-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ingress-certificate
spec:
  secretName: minio-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - minio.home.jonahsserver.com
