apiVersion: v1
kind: Service
metadata:
  name: discord-mcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: discord-mcp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
