apiVersion: apps/v1
kind: Deployment
metadata:
  name: oswald-ai
  labels:
    app: oswald-ai
spec:
  replicas: 0
  selector:
    matchLabels:
      app: oswald-ai
  template:
    metadata:
      labels:
        app: oswald-ai
    spec:
      containers:
        - name: oswald-ai
          image: ghcr.io/jonahgcarpenter/oswald-ai/oswald-ai:v2.0.0-beta.0 # {"$imagepolicy": "flux-system:oswald-ai"}
          envFrom:
            - configMapRef:
                name: oswald-ai-config
            - secretRef:
                name: oswald-ai-secret
