apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oswald-ai
resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - config-map.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
