apiVersion: apps/v1
kind: Deployment
metadata:
  name: alp-web
  labels:
    app: alp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alp-web
  template:
    metadata:
      labels:
        app: alp-web
    spec:
      containers:
        - name: alp-web
          image: ghcr.io/jonahgcarpenter/aprilslilpugs/aprilslilpugs:v2.0.3
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: alp-web-secrets
