apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aprilslilpugs
resources:
  - namespace.yaml
  - sealed-web-secrets.yaml
  - deployment.yaml
  - service.yaml
  - external-services.yaml
  - gateway.yaml
