apiVersion: v1
kind: Service
metadata:
  name: aprilslilpugs-service
  labels:
    app: aprilslilpugs
spec:
  type: LoadBalancer
  selector:
    app: aprilslilpugs
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
